http://localhost:8000/api/foto

### Register user1
POST http://localhost:8000/api/auth/register
Content-Type: application/json
Accept: application/json

{
    "username": "user1",
    "email": "user1@gmail.com",
    "password": "rahasia123"
}

### Register user2
POST http://localhost:8000/api/auth/register
Content-Type: application/json
Accept: application/json

{
    "username": "user2",
    "email": "user2@gmail.com",
    "password": "rahasia123"
}


### Login user1
POST http://localhost:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "username": "user1",
    "password": "rahasia123"
}

### Login user2
POST http://localhost:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "username": "user2",
    "password": "rahasia123"
}


### Get Detail User
GET http://localhost:8000/api/user
Content-Type: application/json
Accept: application/json
Authorization: Bearer <token user here>

{}


### Logout User
DELETE http://localhost:8000/api/auth/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer <token user here>

{}
