### Create a New Note
POST http://localhost:8000/api/notes
Content-Type: multipart/form-data; boundary=boundary
Accept: application/json
Authorization: Bearer <token user here>

--boundary
Content-Disposition: form-data; name="judul"

Masukkan judul catatan disini
--boundary
Content-Disposition: form-data; name="deskripsi"

Masukkan deskripsi catatan disini
--boundary
Content-Disposition: form-data; name="harga"

24500
--boundary
Content-Disposition: form-data; name="tag_id[]"

1
--boundary
Content-Disposition: form-data; name="tag_id[]"

3
--boundary
Content-Disposition: form-data; name="fakultas_id"

7
--boundary
Content-Disposition: form-data; name="prodi_id"

2
--boundary
Content-Disposition: form-data; name="semester_id"

3
--boundary
Content-Disposition: form-data; name="matkul_id"

2
--boundary
Content-Disposition: form-data; name="files[]"; filename="Absen Kelas.jpeg"
Content-Type: image/png

< E:/Telkom University/Absen Kelas.jpeg
--boundary
Content-Disposition: form-data; name="files[]"; filename="Nilai EPrT 2023.pdf"
Content-Type: image/png

< E:/Telkom University/Nilai EPrT 2023.pdf
--boundary--



### Get All Notes
GET http://localhost:8000/api/notes
Accept: application/json
Content-Type: application/json
Authorization: Bearer <token user here>

{}





### Get Notes on Profile
GET http://localhost:8000/api/profile/notes
Accept: application/json
Content-Type: application/json
Authorization: Bearer <token user here>

{}




### Get Note Detail with note_id 12
GET http://localhost:8000/api/notes/12
Accept: application/json
Content-Type: application/json
Authorization: Bearer <token user here>

{}


### Get Note Detail with note_id 50
GET http://localhost:8000/api/notes/50
Accept: application/json
Content-Type: application/json
Authorization: Bearer <token user here>

{}




### Like a Note
POST http://localhost:8000/api/notes/12/like
Content-Type: application/json
Accept: application/json
Authorization: Bearer <token user here>

{}

### Unlike a Note
DELETE http://localhost:8000/api/notes/12/like
Content-Type: application/json
Accept: application/json
Authorization: Bearer <token user here>

{}

### Add Note to Favorite
POST http://localhost:8000/api/notes/12/favorite
Content-Type: application/json
Accept: application/json
Authorization: Bearer <token user here>

{}

### Remove Note from Favorite
DELETE http://localhost:8000/api/notes/12/favorite
Content-Type: application/json
Accept: application/json
Authorization: Bearer <token user here>

{}






### Buy Note
POST http://localhost:8000/api/notes/4/buy
Authorization: Bearer <token user here>
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="bukti_pembayaran"; filename="bukti_bayar.jpg"
Content-Type: image/jpeg

< G:/bukti-bayar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--





### Get Note Files (Only for purchased notes or seller's note)
GET http://localhost:8000/api/notes/4/files
Content-Type: application/json
Accept: application/json
Authorization: Bearer <token user here>

{}
