### GET User Profile Data
GET http://localhost:8000/api/profile
Content-Type: application/json
Accept: application/json
Authorization: Bearer <token user here>

{}



### GET User QR Code
GET http://localhost:8000/api/profile/qr-code
Content-Type: application/json
Accept: application/json
Authorization: Bearer <token user here>

{}

### POST Upload QR Code
POST http://localhost:8000/api/profile/qr-code
Authorization: Bearer <token user here>
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="qr_code"; filename="qr_code_sample.png"
Content-Type: image/png

< E:/Telkom University/Chevalier/Notery/data dummy notery/notesample.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
